namespace SmartMirror.Enums
{
    public enum Message
    {
        HOME,
        TIME,
        WEATHER,
        LIGHT,
        WEATHERFORECAST,
        QUOTE,
        NEWS_SPORTS,
        NEWS_BUSINESS,
        NEWS_ENTERTAINMENT,
        NEWS_HEALTH,
        NEWS_SCIENCE,
        NEWS_TECHNOLOGY,
        RELOAD,
        SCROLL_UP,
        SCROLL_DOWN,
        NAVIGATE_BACKWARDS,
        NAVIGATE_FOREWARDS,
        SPEECH_TIME,
        SPEECH_WEATHER_TOMORROW,
        SPEECH_WEATHER_DAYAFTERTOMORROW,
        SPEECH_WEATHER_TEMPERATURE,
        SPEECH_SUNRISE,
        SPEECH_SUNSET,
        SPEECH_NAME,
        SPEECH_LOOK,
        SPEECH_GENDER,
        UNKNOWN
    }
}